export enum WorkflowType {
  STUDENT_ADMISSION = 'STUDENT_ADMISSION',
  TEACHER_RECRUITMENT = 'TEACHER_RECRUITMENT',
}

export enum StepType {
  APPROVAL = 'APPROVAL',
  INTERVIEW = 'INTERVIEW',
  EVALUATION = 'EVALUATION',
  REVIEW = 'REVIEW',
  NOTIFICATION = 'NOTIFICATION',
}

export enum WorkflowStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REGISTERED = 'REGISTERED',
  CANCELLED = 'CANCELLED',
}

export enum TaskStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
